# Generated by Django 2.0.13 on 2019-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlee', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='IMAGE',
            field=models.ImageField(default='media/default_image.jpg', upload_to=''),
        ),
    ]
