# Generated by Django 2.0.13 on 2019-07-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djlee', '0003_store_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='URL',
            new_name='IMAGENAME',
        ),
    ]
