# Generated by Django 2.0.13 on 2019-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djlee', '0004_auto_20190715_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPSX', models.CharField(max_length=50)),
                ('GPSY', models.CharField(max_length=50)),
                ('LARG_CATE', models.CharField(max_length=50)),
                ('MID_CATE', models.CharField(max_length=50)),
                ('SMALL_CATE', models.CharField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('IMAGENAME', models.CharField(max_length=50)),
                ('IMAGE', models.ImageField(default='media/default_image.jpg', upload_to='')),
            ],
        ),
    ]
