# Generated by Django 2.0.13 on 2019-07-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djlee', '0005_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
